# -*- coding: utf-8 -*-
import random
import streamlit as st

st.set_page_config(page_title="Estudio IVA", layout="centered")

QUESTIONS = [
    {"id": 1, "topic": "Ambito territorial", "question": "Cual de los siguientes territorios esta excluido del ambito de aplicacion del IVA espanol?", "options": {"A": "Mallorca", "B": "Menorca", "C": "Canarias", "D": "Ibiza"}, "answer": "C", "explanation": "Canarias esta excluida del ambito de aplicacion del IVA.", "reference": "LIVA arts. 1 y 3"},
    {"id": 2, "topic": "Ambito territorial", "question": "Ceuta y Melilla, a efectos del IVA espanol:", "options": {"A": "Forman parte del TAI", "B": "Estan excluidas del TAI", "C": "Tributan siempre como operaciones interiores", "D": "Solo Ceuta esta excluida"}, "answer": "B", "explanation": "Ceuta y Melilla estan excluidas del territorio de aplicacion del impuesto.", "reference": "LIVA arts. 1 y 3"},
    {"id": 3, "topic": "Naturaleza", "question": "El IVA es, juridicamente, un impuesto:", "options": {"A": "Directo sobre la renta", "B": "Indirecto sobre el consumo", "C": "Patrimonial", "D": "Personal"}, "answer": "B", "explanation": "El IVA es un impuesto indirecto que recae sobre el consumo.", "reference": "Apuntes IVA, naturaleza del impuesto"},
    {"id": 4, "topic": "Hecho imponible", "question": "Con caracter general, estan sujetas al IVA las entregas de bienes y prestaciones de servicios realizadas por empresarios o profesionales:", "options": {"A": "Solo si son habituales", "B": "A titulo oneroso, habitual u ocasionalmente, en el desarrollo de su actividad", "C": "Solo si existe factura completa", "D": "Solo si el destinatario es empresario"}, "answer": "B", "explanation": "La regla general exige operacion onerosa realizada por empresario o profesional en el desarrollo de su actividad, habitual u ocasionalmente.", "reference": "LIVA art. 4.Uno"},
    {"id": 5, "topic": "Hecho imponible", "question": "La sujecion al IVA se produce con independencia de:", "options": {"A": "Los fines o resultados perseguidos", "B": "Que exista beneficio", "C": "Que el destinatario deduzca", "D": "La forma de pago"}, "answer": "A", "explanation": "La sujecion se produce con independencia de los fines o resultados perseguidos.", "reference": "LIVA art. 4.Tres"},
    {"id": 6, "topic": "Hecho imponible", "question": "Las operaciones sujetas al IVA, con caracter general, respecto del ITPAJD modalidad TPO:", "options": {"A": "Tambien quedan sujetas a TPO", "B": "No quedan sujetas a TPO", "C": "Solo quedan sujetas a TPO si no hay factura", "D": "Solo quedan sujetas a TPO si hay exencion en IVA"}, "answer": "B", "explanation": "Las operaciones sujetas al IVA no estaran sujetas a TPO.", "reference": "LIVA art. 4.Cuatro"},
    {"id": 7, "topic": "Empresario o profesional", "question": "Tiene la condicion de empresario o profesional quien ordena por cuenta propia factores de produccion con la finalidad de:", "options": {"A": "Reducir costes personales", "B": "Intervenir en la produccion o distribucion de bienes o servicios", "C": "Conseguir deducciones en IRPF", "D": "Emitir facturas simplificadas"}, "answer": "B", "explanation": "Esa es la definicion legal general de empresario o profesional.", "reference": "LIVA art. 5"},
    {"id": 8, "topic": "Empresario o profesional", "question": "Las sociedades mercantiles, a efectos del IVA:", "options": {"A": "Nunca son empresarios", "B": "Solo son empresarios si tienen empleados", "C": "Se consideran empresarios o profesionales salvo prueba en contrario", "D": "Solo son empresarios si tienen beneficios"}, "answer": "C", "explanation": "Las sociedades mercantiles se consideran empresarios o profesionales salvo prueba en contrario.", "reference": "LIVA art. 5.Uno.b"},
    {"id": 9, "topic": "Empresario o profesional", "question": "Quien explota un bien corporal o incorporal para obtener ingresos continuados en el tiempo:", "options": {"A": "Nunca es empresario", "B": "Puede tener la condicion de empresario o profesional", "C": "Solo es empresario si es SA", "D": "Solo es empresario si vende el bien"}, "answer": "B", "explanation": "La explotacion de bienes para obtener ingresos continuados atribuye la condicion de empresario o profesional.", "reference": "LIVA art. 5.Uno.c"},
    {"id": 10, "topic": "Empresario o profesional", "question": "El arrendador de bienes, en particular:", "options": {"A": "No tiene nunca la condicion de empresario", "B": "Tiene la condicion de empresario o profesional", "C": "Solo la tiene si arrienda a una sociedad", "D": "Solo la tiene con mas de un inmueble"}, "answer": "B", "explanation": "La ley menciona expresamente a los arrendadores.", "reference": "LIVA art. 5.Uno.c"},
    {"id": 11, "topic": "Inicio de actividad", "question": "Las actividades empresariales o profesionales se consideran iniciadas, a efectos del IVA, desde el momento en que:", "options": {"A": "Se emite la primera factura", "B": "Se adquieren bienes o servicios con la intencion, confirmada por elementos objetivos, de destinarlos a la actividad", "C": "Se obtiene el primer beneficio", "D": "Se contrata al primer trabajador"}, "answer": "B", "explanation": "La condicion puede nacer antes de facturar si existe intencion acreditada.", "reference": "LIVA art. 5 y RIVA art. 27"},
    {"id": 12, "topic": "Inicio de actividad", "question": "La acreditacion de la intencion de iniciar una actividad puede efectuarse:", "options": {"A": "Solo con alta censal", "B": "Por cualquiera de los medios de prueba admitidos en derecho", "C": "Solo con escritura publica", "D": "Solo con contrato de alquiler"}, "answer": "B", "explanation": "El RIVA admite cualquier medio de prueba en derecho, y cita algunos ejemplos.", "reference": "RIVA art. 27"},
    {"id": 13, "topic": "Inicio de actividad", "question": "Si el adquirente no acredita que compro bienes o servicios con intencion de destinarlos a una actividad empresarial:", "options": {"A": "Puede deducir el IVA despues si cambia de opinion", "B": "No se considera que adquirio como empresario y no puede deducir esas cuotas", "C": "Puede deducir solo el 50 por ciento", "D": "Puede deducir si conserva la factura cuatro anos"}, "answer": "B", "explanation": "Sin acreditacion de esa intencion inicial, no nace el derecho a deducir por esas adquisiciones.", "reference": "RIVA art. 27"},
    {"id": 14, "topic": "Entrega de bienes", "question": "A efectos del IVA, una entrega de bienes consiste en:", "options": {"A": "La transmision formal de la propiedad siempre", "B": "La transmision del poder de disposicion sobre bienes corporales", "C": "Cualquier pago anticipado", "D": "Toda prestacion a cambio de precio"}, "answer": "B", "explanation": "La entrega de bienes se define por la transmision del poder de disposicion.", "reference": "LIVA art. 8.Uno"},
    {"id": 15, "topic": "Entrega de bienes", "question": "En IVA, tienen la consideracion de bienes corporales, entre otros:", "options": {"A": "Solo los inmuebles", "B": "Gas, calor, frio y energia electrica", "C": "Solo bienes tangibles tradicionales", "D": "Solo mercancias almacenables"}, "answer": "B", "explanation": "La ley incluye expresamente determinadas modalidades de energia.", "reference": "LIVA art. 8"},
    {"id": 16, "topic": "Entrega de bienes", "question": "Una ejecucion de obra de construccion o rehabilitacion de edificacion se considera entrega de bienes cuando el empresario aporta materiales cuyo coste:", "options": {"A": "Excede del 10 por ciento de la base imponible", "B": "Excede del 25 por ciento", "C": "Excede del 40 por ciento", "D": "Excede del 50 por ciento"}, "answer": "C", "explanation": "La ley fija el umbral del 40 por ciento de la base imponible.", "reference": "LIVA art. 8"},
    {"id": 17, "topic": "Entrega de bienes", "question": "Las aportaciones no dinerarias de elementos del patrimonio empresarial a sociedades, con caracter general, se consideran:", "options": {"A": "Prestaciones de servicios", "B": "Entregas de bienes", "C": "Operaciones no sujetas siempre", "D": "Importaciones"}, "answer": "B", "explanation": "La ley las incluye en el concepto de entrega de bienes.", "reference": "LIVA art. 8"},
    {"id": 18, "topic": "No sujecion", "question": "Los supuestos de no sujecion al IVA delimitan el hecho imponible desde un punto de vista:", "options": {"A": "Solo temporal", "B": "Negativo", "C": "Sancionador", "D": "Censal"}, "answer": "B", "explanation": "La no sujecion completa negativamente la delimitacion del hecho imponible.", "reference": "Apuntes IVA, no sujecion"},
    {"id": 19, "topic": "Importaciones", "question": "Las importaciones de bienes estan sujetas al IVA:", "options": {"A": "Solo si el importador es empresario", "B": "Cualquiera que sea el fin a que se destinen y la condicion del importador", "C": "Solo cuando procedan de terceros paises fuera de la UE", "D": "Solo si existe arancel"}, "answer": "B", "explanation": "La importacion se grava cualquiera que sea el fin o la condicion del importador.", "reference": "LIVA art. 17 y Apuntes IVA"},
    {"id": 20, "topic": "Importaciones", "question": "La entrada en Peninsula o Baleares de bienes procedentes de Canarias constituye:", "options": {"A": "Una entrega interior", "B": "Una adquisicion intracomunitaria", "C": "Una importacion", "D": "Una operacion no sujeta"}, "answer": "C", "explanation": "Canarias esta fuera del TAI, de modo que la entrada en Peninsula o Baleares constituye importacion.", "reference": "Apuntes IVA, importaciones"},
    {"id": 21, "topic": "Importaciones", "question": "La entrada en Peninsula o Baleares de bienes procedentes de Ceuta y Melilla constituye:", "options": {"A": "Una adquisicion intracomunitaria", "B": "Una importacion", "C": "Una entrega interior exenta", "D": "Una operacion no sujeta"}, "answer": "B", "explanation": "La entrada desde Ceuta y Melilla se trata como importacion.", "reference": "Apuntes IVA, importaciones"},
    {"id": 22, "topic": "Importaciones", "question": "En las importaciones, el sujeto pasivo es:", "options": {"A": "El transportista", "B": "Quien realiza la importacion", "C": "Siempre el destinatario final", "D": "El agente de aduanas"}, "answer": "B", "explanation": "El sujeto pasivo de las importaciones es quien las realiza.", "reference": "LIVA art. 86 y Apuntes IVA"},
    {"id": 23, "topic": "Devengo", "question": "En las importaciones, el devengo del IVA se produce:", "options": {"A": "Con la emision de la factura del proveedor", "B": "Cuando hubiera tenido lugar el devengo de los derechos de importacion", "C": "Con el pago del precio", "D": "Al cierre del trimestre"}, "answer": "B", "explanation": "El devengo se vincula al momento del devengo de los derechos de importacion conforme a la legislacion aduanera.", "reference": "LIVA art. 77 y Apuntes IVA"},
    {"id": 24, "topic": "Devengo", "question": "En las adquisiciones intracomunitarias de bienes, los pagos anticipados:", "options": {"A": "Provocan el devengo siempre", "B": "No provocan el devengo", "C": "Provocan el devengo solo si hay factura", "D": "Provocan el devengo si el vendedor es espanol"}, "answer": "B", "explanation": "Los pagos anticipados no provocan el devengo en las AIB.", "reference": "Apuntes IVA, devengo de operaciones intracomunitarias"},
    {"id": 25, "topic": "Adquisiciones intracomunitarias", "question": "El documento acreditativo de una adquisicion intracomunitaria de bienes es, segun los apuntes:", "options": {"A": "La factura simplificada del adquirente", "B": "La factura original emitida por el proveedor extranjero", "C": "Un recibo interno", "D": "El modelo 303"}, "answer": "B", "explanation": "Los apuntes indican que el documento acreditativo es la factura original del proveedor extranjero.", "reference": "Apuntes IVA, AIB"},
    {"id": 26, "topic": "Adquisiciones intracomunitarias", "question": "En una adquisicion intracomunitaria de bienes, el sujeto pasivo debe contabilizar simultaneamente:", "options": {"A": "Un IVA devengado y un IVA soportado", "B": "Solo IVA soportado", "C": "Solo IVA repercutido", "D": "Ningun IVA"}, "answer": "A", "explanation": "En la autorrepercusion se contabiliza IVA devengado y soportado deducible si concurren los requisitos.", "reference": "Apuntes IVA, AIB"},
    {"id": 27, "topic": "Exenciones", "question": "Las entregas intracomunitarias de bienes estan exentas, en esencia, cuando:", "options": {"A": "Siempre que el comprador sea consumidor final", "B": "Se remiten de un Estado miembro a otro y el adquirente es sujeto pasivo o persona juridica que no actua como tal en los terminos legales", "C": "Siempre que exista transporte", "D": "Solo si se expide factura simplificada"}, "answer": "B", "explanation": "La exencion se conecta con la adquisicion intracomunitaria gravada en destino y con la condicion del adquirente.", "reference": "LIVA art. 25 y Apuntes IVA"},
    {"id": 28, "topic": "Exenciones", "question": "Segun los apuntes, estan exentas las entregas de bienes expedidas o transportadas fuera de la Comunidad por el adquirente no establecido o por un tercero en su nombre y por su cuenta. Se trata de una exencion del art.:", "options": {"A": "17 LIVA", "B": "21 LIVA", "C": "68 LIVA", "D": "86 LIVA"}, "answer": "B", "explanation": "Los apuntes citan expresamente el articulo 21 LIVA para estas exportaciones.", "reference": "LIVA art. 21 y Apuntes IVA"},
    {"id": 29, "topic": "Exenciones", "question": "Entre las adquisiciones intracomunitarias exentas figuran las operaciones triangulares cuando concurren determinados requisitos. Uno de ellos es que el adquirente intracomunitario:", "options": {"A": "Este establecido e identificado en Espana", "B": "No este establecido ni identificado en Espana y si en otro Estado miembro", "C": "Sea siempre consumidor final", "D": "Sea una administracion publica espanola"}, "answer": "B", "explanation": "Ese es uno de los requisitos que recogen los apuntes para la exencion en operaciones triangulares.", "reference": "LIVA art. 26 y Apuntes IVA"},
    {"id": 30, "topic": "Lugar de realizacion", "question": "Las entregas de bienes que no sean objeto de expedicion o transporte se entienden realizadas en Espana cuando:", "options": {"A": "Se paguen en euros", "B": "Los bienes se pongan a disposicion del adquirente en territorio espanol", "C": "El vendedor sea espanol", "D": "El comprador sea empresario"}, "answer": "B", "explanation": "Ese es el criterio general para entregas sin expedicion o transporte.", "reference": "LIVA art. 68.Uno y Apuntes IVA"},
    {"id": 31, "topic": "Lugar de realizacion", "question": "Las entregas de bienes muebles corporales objeto de expedicion o transporte se entienden realizadas en Espana cuando:", "options": {"A": "Finalicen en Espana", "B": "La expedicion o transporte se inicien en Espana", "C": "El destinatario sea espanol", "D": "El pago se realice en Espana"}, "answer": "B", "explanation": "El criterio general atiende al lugar de inicio de la expedicion o transporte.", "reference": "LIVA art. 68.Dos y Apuntes IVA"},
    {"id": 32, "topic": "Lugar de realizacion", "question": "Las entregas de bienes que deban ser objeto de instalacion o montaje antes de su puesta a disposicion se entienden realizadas en Espana cuando:", "options": {"A": "El vendedor tenga sede en Espana", "B": "La instalacion o montaje se ultime en Espana y suponga inmovilizacion de los bienes", "C": "La obra dure mas de seis meses", "D": "El comprador lo solicite"}, "answer": "B", "explanation": "La ley exige que la instalacion se ultime en Espana y que implique inmovilizacion.", "reference": "LIVA art. 68.Dos y Apuntes IVA"},
    {"id": 33, "topic": "Lugar de realizacion", "question": "Las entregas de bienes inmuebles se entienden realizadas en Espana cuando:", "options": {"A": "El transmitente resida en Espana", "B": "El adquirente resida en Espana", "C": "Los inmuebles radiquen en Espana", "D": "Se otorgue escritura publica en Espana"}, "answer": "C", "explanation": "El criterio de localizacion atiende a la situacion del inmueble.", "reference": "LIVA art. 68 y Apuntes IVA"},
    {"id": 34, "topic": "Lugar de realizacion", "question": "Las ventas a distancia intracomunitarias de bienes se entienden realizadas en Espana cuando:", "options": {"A": "El lugar de llegada de la expedicion o transporte con destino al cliente sea Espana", "B": "El vendedor sea espanol", "C": "El cliente sea empresario", "D": "Los bienes salgan de Espana"}, "answer": "A", "explanation": "Los apuntes identifican Espana como lugar de realizacion cuando es el lugar de llegada al cliente.", "reference": "LIVA art. 68.3 y Apuntes IVA"},
    {"id": 35, "topic": "Base imponible", "question": "En las importaciones, la base imponible resulta, en general, de adicionar al valor en aduana:", "options": {"A": "Solo el IVA", "B": "Los impuestos y gravamenes distintos del IVA y ciertos gastos accesorios hasta el primer lugar de destino", "C": "Solo el arancel", "D": "Solo los gastos posteriores al destino final"}, "answer": "B", "explanation": "La base imponible de importacion se construye anadiendo esos conceptos al valor en aduana.", "reference": "LIVA art. 83 y Apuntes IVA"},
    {"id": 36, "topic": "Base imponible", "question": "Si el importe de la contraprestacion no resulta conocido en el momento del devengo:", "options": {"A": "No nace el impuesto", "B": "Debe fijarse provisionalmente aplicando criterios fundados y rectificarse despues", "C": "Debe suspenderse la operacion", "D": "Debe emitirse siempre factura simplificada"}, "answer": "B", "explanation": "Los apuntes recogen esa regla de fijacion provisional y rectificacion posterior.", "reference": "Apuntes IVA, base imponible"},
    {"id": 37, "topic": "Base imponible", "question": "La modificacion al alza de la base imponible procede cuando el sujeto pasivo, tras reclamar judicialmente el cobro de un credito, desiste de la reclamacion o alcanza un acuerdo de cobro. En ese caso el plazo para rectificar es de:", "options": {"A": "15 dias", "B": "1 mes", "C": "3 meses", "D": "4 anos"}, "answer": "B", "explanation": "Los apuntes senalan un plazo de un mes desde el desistimiento o acuerdo de cobro.", "reference": "Apuntes IVA, modificacion de la base imponible"},
    {"id": 38, "topic": "Base imponible", "question": "No procede, con caracter general, la modificacion de la base imponible por creditos incobrables o supuestos afines cuando el credito esta garantizado con garantia real:", "options": {"A": "En toda su extension", "B": "En la parte garantizada", "C": "Solo si es hipotecaria", "D": "Solo si supera 3000 euros"}, "answer": "B", "explanation": "Los apuntes excluyen la modificacion en la parte garantizada.", "reference": "Apuntes IVA, modificacion de la base imponible"},
    {"id": 39, "topic": "Base imponible", "question": "Tampoco procede, con caracter general, la modificacion de la base imponible cuando los creditos son entre personas o entidades:", "options": {"A": "No establecidas", "B": "Vinculadas", "C": "Publicas", "D": "Concurso"}, "answer": "B", "explanation": "Los apuntes citan expresamente los creditos entre vinculadas como supuesto de no procedencia.", "reference": "Apuntes IVA, modificacion de la base imponible"},
    {"id": 40, "topic": "Base imponible", "question": "La rectificacion de la base imponible por estas causas debe realizarse mediante:", "options": {"A": "Asiento interno", "B": "Factura rectificativa", "C": "Nueva factura simplificada", "D": "Recibo bancario"}, "answer": "B", "explanation": "La rectificacion debe documentarse mediante factura rectificativa.", "reference": "Reglamento de facturacion art. 15 y Apuntes IVA"},
    {"id": 41, "topic": "Sujeto pasivo", "question": "En las adquisiciones intracomunitarias de bienes, el adquirente, con caracter general:", "options": {"A": "No realiza autorrepercusion", "B": "Autoliquida la operacion", "C": "Solo soporta IVA extranjero", "D": "Es sujeto pasivo solo si es particular"}, "answer": "B", "explanation": "Los apuntes indican que el sujeto pasivo debe autoliquidar la operacion.", "reference": "Apuntes IVA, AIB"},
    {"id": 42, "topic": "Deducciones", "question": "El IVA soportado en una adquisicion intracomunitaria sera deducible si:", "options": {"A": "Se emite factura simplificada", "B": "Se cumplen los requisitos de los arts. 92 y siguientes LIVA", "C": "La operacion es gratuita", "D": "El proveedor extranjero no lo repercute"}, "answer": "B", "explanation": "La deduccion exige el cumplimiento de los requisitos legales generales.", "reference": "LIVA arts. 92 y ss. y Apuntes IVA"},
    {"id": 43, "topic": "Deducciones", "question": "No tienen la consideracion de bienes de inversion, entre otros:", "options": {"A": "Los inmuebles destinados a la actividad", "B": "Los accesorios y piezas de recambio para reparar bienes de inversion", "C": "La maquinaria de uso duradero", "D": "Los vehiculos afectos si cumplen requisitos"}, "answer": "B", "explanation": "Los accesorios y recambios para reparacion quedan excluidos del concepto de bien de inversion.", "reference": "LIVA art. 108 y Apuntes IVA"},
    {"id": 44, "topic": "Deducciones", "question": "No tendra la consideracion de bien de inversion, por su valor, cualquier bien cuyo valor de adquisicion sea inferior a:", "options": {"A": "300 euros", "B": "601,01 euros", "C": "3.005,61 euros", "D": "6.000 euros"}, "answer": "C", "explanation": "Los apuntes citan el umbral legal de 3.005,61 euros.", "reference": "LIVA art. 108 y Apuntes IVA"},
    {"id": 45, "topic": "Deducciones", "question": "El IVA de los bienes de inversion se deduce, en principio:", "options": {"A": "Solo al final del periodo de regularizacion", "B": "En el ejercicio en que se adquieren, si se cumplen los requisitos", "C": "Siempre en cinco anos", "D": "Solo si no hay prorrata"}, "answer": "B", "explanation": "La deduccion se practica inicialmente en el ejercicio de adquisicion, sin perjuicio de regularizaciones.", "reference": "Apuntes IVA, bienes de inversion"},
    {"id": 46, "topic": "Prorrata", "question": "Segun los apuntes, en prorrata especial las adquisiciones comunes se deducen aplicando el porcentaje que resulte de la prorrata general sobre dichas cuotas comunes:", "options": {"A": "Verdadero", "B": "Falso", "C": "Solo en importaciones", "D": "Solo si existe recargo de equivalencia"}, "answer": "A", "explanation": "Los apuntes ilustran ese funcionamiento con un ejemplo numerico.", "reference": "Apuntes IVA, prorrata especial"},
    {"id": 47, "topic": "Regimenes especiales", "question": "En el recargo de equivalencia, el comerciante minorista, con caracter general:", "options": {"A": "Presenta autoliquidaciones periodicas de IVA", "B": "No presenta declaracion periodica alguna por IVA", "C": "Puede deducir el IVA soportado", "D": "Debe emitir siempre factura completa"}, "answer": "B", "explanation": "Una de las notas del regimen es la no presentacion de declaraciones periodicas por IVA.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 48, "topic": "Regimenes especiales", "question": "En recargo de equivalencia, el IVA soportado, incluido el recargo:", "options": {"A": "Se deduce integramente", "B": "No se puede deducir ni recuperar", "C": "Se deduce solo el recargo", "D": "Se devuelve anualmente"}, "answer": "B", "explanation": "Los apuntes lo describen como mayor coste de adquisicion.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 49, "topic": "Regimenes especiales", "question": "El recargo de equivalencia general aplicable sobre entregas al minorista es del:", "options": {"A": "1,4 por ciento", "B": "5,2 por ciento", "C": "0,5 por ciento", "D": "1,75 por ciento"}, "answer": "B", "explanation": "Ese es el porcentaje general recogido en los apuntes.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 50, "topic": "Regimenes especiales", "question": "El recargo de equivalencia para entregas sometidas al tipo del 10 por ciento es del:", "options": {"A": "0,5 por ciento", "B": "1,75 por ciento", "C": "1,4 por ciento", "D": "5,2 por ciento"}, "answer": "C", "explanation": "Los apuntes fijan el 1,4 por ciento para las entregas al tipo del 10 por ciento.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 51, "topic": "Regimenes especiales", "question": "El recargo de equivalencia para entregas sometidas al 4 por ciento es del:", "options": {"A": "0,5 por ciento", "B": "1,4 por ciento", "C": "1,75 por ciento", "D": "5,2 por ciento"}, "answer": "A", "explanation": "Los apuntes recogen un recargo del 0,5 por ciento para el tipo del 4 por ciento.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 52, "topic": "Regimenes especiales", "question": "El recargo de equivalencia para labores del tabaco es del:", "options": {"A": "5,2 por ciento", "B": "1,4 por ciento", "C": "1,75 por ciento", "D": "0,5 por ciento"}, "answer": "C", "explanation": "Los apuntes fijan el 1,75 por ciento para labores del tabaco.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 53, "topic": "Regimenes especiales", "question": "La base imponible sobre la que se aplica el recargo de equivalencia es:", "options": {"A": "La mitad de la base del IVA", "B": "La misma establecida con caracter general en el IVA", "C": "Solo el margen del minorista", "D": "El importe sin gastos accesorios"}, "answer": "B", "explanation": "Los apuntes indican expresamente que es la misma base imponible que la del IVA.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 54, "topic": "Regimenes especiales", "question": "No existe obligacion de repercutir el recargo de equivalencia, entre otros supuestos, cuando quien efectua la entrega es tambien sujeto pasivo sometido a:", "options": {"A": "Recargo de equivalencia", "B": "Criterio de caja", "C": "Grupo de entidades", "D": "Agencias de viajes"}, "answer": "A", "explanation": "Los apuntes recogen esa excepcion expresamente.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 55, "topic": "Regimenes especiales", "question": "La principal ventaja del recargo de equivalencia para el pequeno comerciante es:", "options": {"A": "La deduccion integra del IVA soportado", "B": "La simplificacion administrativa al no presentar declaraciones de IVA ni llevar los mismos libros", "C": "La exencion total del impuesto", "D": "La tributacion al 4 por ciento"}, "answer": "B", "explanation": "Los apuntes destacan la simplificacion administrativa como ventaja principal.", "reference": "Apuntes IVA, recargo de equivalencia"},
    {"id": 56, "topic": "Facturacion", "question": "La obligacion general de expedir factura corresponde:", "options": {"A": "Solo a sociedades mercantiles", "B": "A empresarios o profesionales por las operaciones que realicen, salvo excepciones", "C": "Solo cuando el cliente la pida", "D": "Solo si la operacion supera 400 euros"}, "answer": "B", "explanation": "Esa es la regla general del articulo 2 del Reglamento de facturacion.", "reference": "Reglamento de facturacion art. 2"},
    {"id": 57, "topic": "Facturacion", "question": "La factura simplificada puede expedirse con caracter general cuando su importe no exceda de:", "options": {"A": "300 euros IVA incluido", "B": "400 euros IVA incluido", "C": "1000 euros IVA excluido", "D": "3000 euros en cualquier caso"}, "answer": "B", "explanation": "El articulo 4.1.a fija el umbral general de 400 euros IVA incluido.", "reference": "Reglamento de facturacion art. 4"},
    {"id": 58, "topic": "Facturacion", "question": "Tambien puede expedirse factura simplificada cuando deba expedirse:", "options": {"A": "Factura recapitulativa", "B": "Factura rectificativa", "C": "Factura electronica", "D": "Factura por terceros"}, "answer": "B", "explanation": "El articulo 4 permite factura simplificada cuando deba expedirse una factura rectificativa.", "reference": "Reglamento de facturacion art. 4"},
    {"id": 59, "topic": "Facturacion", "question": "En determinados supuestos tasados, puede expedirse factura simplificada cuando su importe no exceda de:", "options": {"A": "400 euros IVA incluido", "B": "1000 euros IVA excluido", "C": "3000 euros IVA incluido", "D": "6000 euros IVA incluido"}, "answer": "C", "explanation": "El articulo 4.2 fija el umbral de 3000 euros IVA incluido para ciertos sectores y operaciones.", "reference": "Reglamento de facturacion art. 4"},
    {"id": 60, "topic": "Facturacion", "question": "Entre las operaciones en las que puede expedirse factura simplificada hasta 3000 euros se encuentra:", "options": {"A": "Entregas intracomunitarias exentas", "B": "Servicios de hosteleria y restauracion", "C": "Todas las prestaciones B2B", "D": "Importaciones"}, "answer": "B", "explanation": "El articulo 4.2 incluye expresamente servicios de hosteleria y restauracion.", "reference": "Reglamento de facturacion art. 4"},
    {"id": 61, "topic": "Facturacion", "question": "No puede expedirse factura simplificada por las entregas de bienes destinadas a otro Estado miembro a que se refiere:", "options": {"A": "El articulo 25 LIVA", "B": "El articulo 80 LIVA", "C": "El articulo 92 LIVA", "D": "El articulo 108 LIVA"}, "answer": "A", "explanation": "El articulo 4.4 del Reglamento remite expresamente al articulo 25 LIVA.", "reference": "Reglamento de facturacion art. 4.4"},
    {"id": 62, "topic": "Facturacion", "question": "Las facturas pueden expedirse por cualquier medio, en papel o en formato electronico, siempre que se garantice, entre otros extremos:", "options": {"A": "Solo el cobro", "B": "Autenticidad del origen, integridad del contenido y legibilidad", "C": "Solo la fecha de emision", "D": "Solo la firma manuscrita"}, "answer": "B", "explanation": "Esos son los requisitos esenciales del articulo 8.", "reference": "Reglamento de facturacion art. 8"},
    {"id": 63, "topic": "Facturacion", "question": "La autenticidad del origen de la factura garantiza:", "options": {"A": "La forma de pago", "B": "La identidad del obligado a su expedicion y del emisor", "C": "El tipo de IVA aplicable", "D": "La deducibilidad del IVA"}, "answer": "B", "explanation": "Asi lo define el articulo 8.2 del Reglamento de facturacion.", "reference": "Reglamento de facturacion art. 8.2"},
    {"id": 64, "topic": "Facturacion", "question": "La integridad del contenido de la factura garantiza que:", "options": {"A": "Se haya cobrado", "B": "El contenido no ha sido modificado", "C": "Se haya contabilizado", "D": "La operacion sea deducible"}, "answer": "B", "explanation": "Ese es el concepto legal de integridad del contenido.", "reference": "Reglamento de facturacion art. 8.2"},
    {"id": 65, "topic": "Facturacion", "question": "Los controles de gestion usuales pueden servir para garantizar autenticidad e integridad siempre que permitan crear:", "options": {"A": "Una declaracion censal", "B": "Una pista de auditoria fiable", "C": "Una firma avanzada", "D": "Un asiento de regularizacion"}, "answer": "B", "explanation": "El Reglamento exige que los controles permitan una pista de auditoria fiable.", "reference": "Reglamento de facturacion art. 8.3"},
    {"id": 66, "topic": "Factura electronica", "question": "Se entiende por factura electronica aquella que:", "options": {"A": "Se ajusta al Reglamento y ha sido expedida y recibida en formato electronico", "B": "Solo esta firmada electronicamente", "C": "Solo se envia por email", "D": "Solo se emite entre empresarios"}, "answer": "A", "explanation": "Esa es la definicion reglamentaria de factura electronica.", "reference": "Reglamento de facturacion art. 9"},
    {"id": 67, "topic": "Factura electronica", "question": "La expedicion de factura electronica esta condicionada a que el destinatario:", "options": {"A": "Sea empresario", "B": "Haya dado su consentimiento", "C": "Este en Espana", "D": "Pague por transferencia"}, "answer": "B", "explanation": "El consentimiento del destinatario es requisito expreso.", "reference": "Reglamento de facturacion art. 9.2"},
    {"id": 68, "topic": "Factura electronica", "question": "La autenticidad del origen y la integridad del contenido de la factura electronica pueden garantizarse por:", "options": {"A": "Cualquiera de los medios senalados en el articulo 8", "B": "Solo firma electronica avanzada", "C": "Solo EDI", "D": "Solo medios validados previamente por la AEAT"}, "answer": "A", "explanation": "El articulo 10 remite con caracter general a los medios del articulo 8.", "reference": "Reglamento de facturacion art. 10"},
    {"id": 69, "topic": "Factura electronica", "question": "Entre las formas que, en particular, garantizan autenticidad e integridad de la factura electronica se encuentran:", "options": {"A": "Firma electronica avanzada, EDI y otros medios comunicados y validados", "B": "Solo firma electronica avanzada", "C": "Solo sello de tiempo", "D": "Solo PDF firmado a mano"}, "answer": "A", "explanation": "El articulo 10 enumera esas tres vias particulares.", "reference": "Reglamento de facturacion art. 10"},
    {"id": 70, "topic": "Factura electronica", "question": "En lotes que incluyan varias facturas electronicas remitidas simultaneamente al mismo destinatario, los detalles comunes:", "options": {"A": "Deben repetirse en todas siempre", "B": "Pueden mencionarse una sola vez si se tiene acceso para cada factura a la totalidad de la informacion", "C": "No pueden omitirse nunca", "D": "Solo pueden agruparse si son simplificadas"}, "answer": "B", "explanation": "El articulo 10.2 permite esa simplificacion con esa condicion.", "reference": "Reglamento de facturacion art. 10.2"},
    {"id": 71, "topic": "Plazos de facturacion", "question": "El Reglamento de facturacion regula el plazo para la expedicion de las facturas en el articulo:", "options": {"A": "8", "B": "9", "C": "11", "D": "15"}, "answer": "C", "explanation": "El indice del Reglamento sitia el plazo de expedicion en el articulo 11.", "reference": "Reglamento de facturacion art. 11"},
    {"id": 72, "topic": "Facturas recapitulativas", "question": "Las facturas recapitulativas se regulan en el articulo:", "options": {"A": "13 del Reglamento de facturacion", "B": "7 del Reglamento de facturacion", "C": "18 del Reglamento de facturacion", "D": "23 del RIVA"}, "answer": "A", "explanation": "El Reglamento regula las facturas recapitulativas en su articulo 13.", "reference": "Reglamento de facturacion art. 13"},
    {"id": 73, "topic": "Facturas rectificativas", "question": "Las facturas rectificativas se regulan en el articulo:", "options": {"A": "4", "B": "11", "C": "15", "D": "23"}, "answer": "C", "explanation": "El articulo 15 regula las facturas rectificativas.", "reference": "Reglamento de facturacion art. 15"},
    {"id": 74, "topic": "Facturas rectificativas", "question": "La factura rectificativa debe expedirse tan pronto como el obligado tenga constancia de las circunstancias que obligan a ello, siempre que no hayan transcurrido desde el devengo o desde las circunstancias del art. 80 LIVA:", "options": {"A": "6 meses", "B": "1 ano", "C": "4 anos", "D": "10 anos"}, "answer": "C", "explanation": "El articulo 15.3 fija el limite temporal de cuatro anos.", "reference": "Reglamento de facturacion art. 15.3"},
    {"id": 75, "topic": "Facturas rectificativas", "question": "La rectificacion de varias facturas puede efectuarse en un unico documento de rectificacion siempre que:", "options": {"A": "Sean todas simplificadas", "B": "Se identifiquen todas las facturas rectificadas", "C": "La AEAT lo autorice siempre", "D": "Sean del mismo trimestre y mismo tipo"}, "answer": "B", "explanation": "El Reglamento permite rectificar varias en un unico documento si se identifican todas.", "reference": "Reglamento de facturacion art. 15.4"},
    {"id": 76, "topic": "Facturas rectificativas", "question": "Cuando la modificacion de la base imponible derive de descuentos o bonificaciones por volumen de operaciones, en la rectificacion:", "options": {"A": "Siempre hay que identificar todas las facturas", "B": "Puede bastar la determinacion del periodo a que se refieren", "C": "Debe emitirse factura simplificada", "D": "No cabe documento unico"}, "answer": "B", "explanation": "En ese caso no es necesaria la identificacion individual de todas las facturas, bastando el periodo.", "reference": "Reglamento de facturacion art. 15.4"},
    {"id": 77, "topic": "Facturas rectificativas", "question": "Una factura expedida en sustitucion o canje de una factura simplificada anterior tendra la condicion de rectificativa:", "options": {"A": "Siempre", "B": "Nunca, si la simplificada inicial cumplia los requisitos del art. 7.1", "C": "Solo si supera 400 euros", "D": "Solo si hay descuento"}, "answer": "B", "explanation": "El articulo 15.6 niega en ese caso la condicion de rectificativa si la simplificada cumplia los requisitos legales.", "reference": "Reglamento de facturacion art. 15.6"},
    {"id": 78, "topic": "Conservacion", "question": "La obligacion de conservacion de facturas y otros documentos se regula en el articulo:", "options": {"A": "17", "B": "19", "C": "21", "D": "24"}, "answer": "B", "explanation": "El indice del Reglamento de facturacion sitia la obligacion de conservacion en el articulo 19.", "reference": "Reglamento de facturacion art. 19"},
    {"id": 79, "topic": "Conservacion", "question": "La conservacion electronica de documentos debe asegurar, entre otros extremos:", "options": {"A": "Solo la visualizacion", "B": "La legibilidad en el formato original y, en su caso, los mecanismos de verificacion", "C": "Solo la descarga", "D": "Solo la impresion"}, "answer": "B", "explanation": "Los apuntes exigen legibilidad, datos asociados y mecanismos de verificacion, en su caso.", "reference": "Apuntes IVA, conservacion electronica"},
    {"id": 80, "topic": "Conservacion", "question": "Los documentos conservados por medios electronicos deben garantizar a la Administracion tributaria, ante requerimiento y sin demora injustificada:", "options": {"A": "Solo impresion", "B": "Acceso en linea, carga remota y utilizacion", "C": "Solo envio por email", "D": "Solo acceso presencial"}, "answer": "B", "explanation": "Esa es la exigencia recogida en los apuntes para la conservacion electronica.", "reference": "Apuntes IVA, conservacion electronica"},
    {"id": 81, "topic": "Conservacion", "question": "El acceso completo de la Administracion a la documentacion conservada electronicamente comprende, entre otras facultades:", "options": {"A": "Visualizacion, busqueda selectiva, copia o descarga en linea e impresion", "B": "Solo visualizacion", "C": "Solo descarga", "D": "Solo impresion y copia"}, "answer": "A", "explanation": "Los apuntes definen asi el acceso completo.", "reference": "Apuntes IVA, conservacion electronica"},
    {"id": 82, "topic": "Conservacion", "question": "Cuando la conservacion se efectue fuera de Espana, la obligacion se considera validamente cumplida solo si:", "options": {"A": "Existe servidor europeo", "B": "Se usan medios electronicos que garanticen acceso en linea, carga remota y utilizacion por la Administracion", "C": "Se legalizan libros", "D": "Se firma con certificado extranjero"}, "answer": "B", "explanation": "Esa es la condicion que recogen los apuntes.", "reference": "Apuntes IVA, conservacion electronica"},
    {"id": 83, "topic": "Conservacion", "question": "Si la conservacion de facturas se realiza fuera de Espana mediante medios electronicos con las garantias exigidas, debe comunicarse previamente esta circunstancia a:", "options": {"A": "TGSS", "B": "AEAT", "C": "Registro Mercantil", "D": "Banco de Espana"}, "answer": "B", "explanation": "Los apuntes exigen comunicacion previa a la Agencia Estatal de Administracion Tributaria.", "reference": "Apuntes IVA, conservacion electronica"},
    {"id": 84, "topic": "Localizacion y transporte UE", "question": "Las entregas de bienes a pasajeros a bordo de un buque, avion o tren, en transporte realizado en el interior de la UE, se entienden realizadas en Espana si:", "options": {"A": "El billete se compra en Espana", "B": "El inicio del transporte se encuentra en Espana y el destino en otro Estado miembro", "C": "El pasajero reside en Espana", "D": "La compania es espanola"}, "answer": "B", "explanation": "Ese es el criterio recogido en los apuntes para esas ventas a bordo.", "reference": "LIVA art. 68 y Apuntes IVA"},
    {"id": 85, "topic": "Importaciones", "question": "Si un bien se introduce en zona franca o deposito franco y luego sale al TAI, la importacion se produce:", "options": {"A": "En el momento de la entrada inicial en la zona", "B": "Cuando el bien sale de esas areas o abandona el regimen", "C": "Nunca", "D": "Al emitir la factura del proveedor"}, "answer": "B", "explanation": "Los apuntes indican que la importacion se produce al salir de las areas o abandonar los regimenes indicados.", "reference": "Apuntes IVA, importaciones"},
    {"id": 86, "topic": "Importaciones", "question": "En las importaciones, una nota definitoria del regimen es que:", "options": {"A": "Puede haber importacion de servicios", "B": "Se requiere la entrada fisica de los bienes", "C": "Solo importan los empresarios", "D": "No puede haber importacion desde Canarias"}, "answer": "B", "explanation": "Los apuntes destacan que se requiere la entrada fisica de los bienes y que no existe importacion de servicios.", "reference": "Apuntes IVA, importaciones"},
    {"id": 87, "topic": "Importaciones", "question": "A diferencia de las adquisiciones intracomunitarias de bienes, en las importaciones:", "options": {"A": "Se exige siempre que el importador sea empresario", "B": "No se exige la condicion de empresario o profesional al importador", "C": "No existe devengo", "D": "No hay base imponible"}, "answer": "B", "explanation": "Los apuntes subrayan que incluso un particular puede realizar este hecho imponible.", "reference": "Apuntes IVA, importaciones"},
    {"id": 88, "topic": "Facturacion", "question": "El contenido de la factura completa se regula en el articulo:", "options": {"A": "6 del Reglamento de facturacion", "B": "7 del Reglamento de facturacion", "C": "9 del Reglamento de facturacion", "D": "13 del Reglamento de facturacion"}, "answer": "A", "explanation": "El indice del Reglamento situa el contenido de la factura en el articulo 6.", "reference": "Reglamento de facturacion art. 6"},
    {"id": 89, "topic": "Facturacion", "question": "El contenido de la factura simplificada se regula en el articulo:", "options": {"A": "4", "B": "6", "C": "7", "D": "15"}, "answer": "C", "explanation": "El contenido de las facturas simplificadas se regula en el articulo 7.", "reference": "Reglamento de facturacion art. 7"},
    {"id": 90, "topic": "Facturacion", "question": "La obligacion de remision de las facturas se regula en el articulo:", "options": {"A": "16", "B": "17", "C": "19", "D": "24"}, "answer": "B", "explanation": "El indice del Reglamento sitia esta materia en el articulo 17.", "reference": "Reglamento de facturacion art. 17"},
    {"id": 91, "topic": "Facturacion", "question": "El plazo para la remision de las facturas se regula en el articulo:", "options": {"A": "18", "B": "11", "C": "20", "D": "24"}, "answer": "A", "explanation": "El indice del Reglamento sitia el plazo de remision en el articulo 18.", "reference": "Reglamento de facturacion art. 18"},
    {"id": 92, "topic": "Facturacion", "question": "La conservacion por medios electronicos se regula en el articulo:", "options": {"A": "19", "B": "20", "C": "21", "D": "23"}, "answer": "C", "explanation": "El indice del Reglamento sitia la conservacion electronica en el articulo 21.", "reference": "Reglamento de facturacion art. 21"},
    {"id": 93, "topic": "Facturacion", "question": "El lugar de conservacion de las facturas y otros documentos se regula en el articulo:", "options": {"A": "20", "B": "21", "C": "22", "D": "23"}, "answer": "C", "explanation": "El indice del Reglamento sitia el lugar de conservacion en el articulo 22.", "reference": "Reglamento de facturacion art. 22"},
    {"id": 94, "topic": "Facturacion", "question": "El acceso de la Administracion tributaria a facturas y otros documentos se regula en el articulo:", "options": {"A": "23", "B": "18", "C": "15", "D": "9"}, "answer": "A", "explanation": "El indice del Reglamento sitia esta materia en el articulo 23.", "reference": "Reglamento de facturacion art. 23"},
    {"id": 95, "topic": "RIVA", "question": "La opcion por la tributacion en el territorio de aplicacion del impuesto de determinadas operaciones intracomunitarias se regula en el RIVA en el articulo:", "options": {"A": "1 bis", "B": "2", "C": "3", "D": "24"}, "answer": "C", "explanation": "El indice del RIVA sitia esa opcion en el articulo 3.", "reference": "RIVA art. 3"},
    {"id": 96, "topic": "RIVA", "question": "Las reglas relacionadas con la localizacion de determinadas operaciones se regulan en el RIVA en el articulo:", "options": {"A": "22", "B": "23", "C": "24", "D": "27"}, "answer": "B", "explanation": "El indice del RIVA sitia esa materia en el articulo 23.", "reference": "RIVA art. 23"},
    {"id": 97, "topic": "RIVA", "question": "La modificacion de la base imponible se regula en el RIVA en el articulo:", "options": {"A": "23 bis", "B": "24", "C": "24 quater", "D": "25"}, "answer": "B", "explanation": "El indice del RIVA situa la modificacion de la base imponible en el articulo 24.", "reference": "RIVA art. 24"},
    {"id": 98, "topic": "RIVA", "question": "La aplicacion de las reglas de inversion del sujeto pasivo se regula en el RIVA en el articulo:", "options": {"A": "24 bis", "B": "24 ter", "C": "24 quater", "D": "24 quinquies"}, "answer": "C", "explanation": "El indice del RIVA la sitia en el articulo 24 quater.", "reference": "RIVA art. 24 quater"},
    {"id": 99, "topic": "RIVA", "question": "Las deducciones de cuotas soportadas antes del inicio de la actividad se regulan en el RIVA en el articulo:", "options": {"A": "24", "B": "27", "C": "28", "D": "30"}, "answer": "B", "explanation": "El indice del RIVA situa esta materia en el articulo 27.", "reference": "RIVA art. 27"},
    {"id": 100, "topic": "VERIFACTU apuntes", "question": "Segun los apuntes, si el contribuyente no utiliza un sistema informatico de facturacion y opta por facturas manuscritas o impresas a maquina, respecto del Reglamento VERIFACTU:", "options": {"A": "Siempre queda obligado", "B": "No esta obligado a cumplir sus disposiciones", "C": "Solo queda obligado si es autonomo", "D": "Solo queda obligado si usa factura simplificada"}, "answer": "B", "explanation": "Los apuntes indican que si no usa un sistema informatico de ese tipo y opta por metodo manual no queda obligada por el Reglamento.", "reference": "Apuntes IVA, reglas del Reglamento VERIFACTU"}
]

TOPICS = ["Todos"] + sorted({q["topic"] for q in QUESTIONS})
MODES = ["Secuencial", "Simulacro 20", "Aleatorio"]

if "setup_done" not in st.session_state:
    st.session_state.setup_done = False
if "queue" not in st.session_state:
    st.session_state.queue = []
if "index" not in st.session_state:
    st.session_state.index = 0
if "answered" not in st.session_state:
    st.session_state.answered = False
if "selected" not in st.session_state:
    st.session_state.selected = None
if "score_ok" not in st.session_state:
    st.session_state.score_ok = 0
if "score_bad" not in st.session_state:
    st.session_state.score_bad = 0
if "current_topic" not in st.session_state:
    st.session_state.current_topic = "Todos"
if "current_mode" not in st.session_state:
    st.session_state.current_mode = "Secuencial"


def build_queue(topic: str, mode: str):
    items = [q for q in QUESTIONS if topic == "Todos" or q["topic"] == topic]
    random.shuffle(items)
    if mode == "Secuencial":
        items.sort(key=lambda x: x["id"])
    elif mode == "Simulacro 20":
        items = items[:20]
    return items


def reset_quiz(topic: str, mode: str):
    st.session_state.current_topic = topic
    st.session_state.current_mode = mode
    st.session_state.queue = build_queue(topic, mode)
    st.session_state.index = 0
    st.session_state.answered = False
    st.session_state.selected = None
    st.session_state.score_ok = 0
    st.session_state.score_bad = 0
    st.session_state.setup_done = True


def current_question():
    if 0 <= st.session_state.index < len(st.session_state.queue):
        return st.session_state.queue[st.session_state.index]
    return None


st.title("Estudio IVA - Test avanzado")

with st.sidebar:
    st.subheader("Marcador")
    total = st.session_state.score_ok + st.session_state.score_bad
    pct = round((st.session_state.score_ok / total) * 100, 2) if total else 0.0
    st.write(f"Aciertos: {st.session_state.score_ok}")
    st.write(f"Errores: {st.session_state.score_bad}")
    st.write(f"Porcentaje: {pct}%")
    if st.session_state.setup_done:
        st.write(f"Tema: {st.session_state.current_topic}")
        st.write(f"Modo: {st.session_state.current_mode}")
        st.write(f"Pregunta: {min(st.session_state.index + 1, max(len(st.session_state.queue), 1))}/{len(st.session_state.queue)}")

if not st.session_state.setup_done:
    st.subheader("Configuracion inicial")
    topic = st.selectbox("Bloque", TOPICS)
    mode = st.selectbox("Modalidad", MODES)
    if st.button("Empezar test"):
        reset_quiz(topic, mode)
        st.rerun()
else:
    q = current_question()
    if q is None:
        st.subheader("Test finalizado")
        total = st.session_state.score_ok + st.session_state.score_bad
        pct = round((st.session_state.score_ok / total) * 100, 2) if total else 0.0
        st.write(f"Aciertos: {st.session_state.score_ok}")
        st.write(f"Errores: {st.session_state.score_bad}")
        st.write(f"Porcentaje: {pct}%")
        col1, col2 = st.columns(2)
        with col1:
            if st.button("Repetir misma configuracion"):
                reset_quiz(st.session_state.current_topic, st.session_state.current_mode)
                st.rerun()
        with col2:
            if st.button("Nueva configuracion"):
                st.session_state.setup_done = False
                st.rerun()
    else:
        st.caption(f"Tema: {q['topic']} | ID: {q['id']}")
        st.subheader(f"Pregunta {st.session_state.index + 1}")
        st.write(q["question"])

        selected = st.radio(
            "Elige una opcion",
            ["A", "B", "C", "D"],
            format_func=lambda x: f"{x}) {q['options'][x]}",
            key=f"radio_{q['id']}"
        )

        col1, col2 = st.columns(2)
        with col1:
            if st.button("Responder") and not st.session_state.answered:
                st.session_state.selected = selected
                st.session_state.answered = True
                if selected == q["answer"]:
                    st.session_state.score_ok += 1
                else:
                    st.session_state.score_bad += 1
                st.rerun()
        with col2:
            if st.button("Cambiar configuracion"):
                st.session_state.setup_done = False
                st.rerun()

        if st.session_state.answered:
            if st.session_state.selected == q["answer"]:
                st.success(f"Correcta. Respuesta: {q['answer']}")
            else:
                st.error(f"Incorrecta. Respuesta correcta: {q['answer']}")
            st.write("Explicacion:", q["explanation"])
            st.write("Referencia:", q["reference"])
            if st.button("Siguiente pregunta"):
                st.session_state.index += 1
                st.session_state.answered = False
                st.session_state.selected = None
                st.rerun()
